name: profile_editor_app
description: A responsive Flutter profile editor with BLoC, Hive, Dio, GoRouter.

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  dio: ^5.4.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  go_router: ^13.0.0
  flutter_form_builder: ^9.1.1
  form_builder_validators: ^9.1.0
  shared_preferences: ^2.2.2
  fluttertoast: ^8.2.4
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.4.8
  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/images/
